# Generated by Django 2.0 on 2018-10-14 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QAsession', '0002_auto_20181014_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qasession',
            name='close_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qasession',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qasession',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qasession',
            name='status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
