# Generated by Django 2.0 on 2018-11-25 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QAsession', '0007_auto_20181118_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='qa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QAsession.qasession'),
        ),
    ]
